"""redirects foreign key to users

Revision ID: 2cf833ae9cf
Revises: 3471f466dda
Create Date: 2015-10-19 14:53:08.359562

"""

# revision identifiers, used by Alembic.
revision = '2cf833ae9cf'
down_revision = '3471f466dda'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('redirects', sa.Column('created_by', postgresql.UUID(as_uuid=True), nullable=False))
    op.create_foreign_key(op.f('fk_redirects_created_by_users'), 'redirects', 'users', ['created_by'], ['uuid'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_redirects_created_by_users'), 'redirects', type_='foreignkey')
    op.drop_column('redirects', 'created_by')
    ### end Alembic commands ###
