"""users table

Revision ID: 3471f466dda
Revises: 734acfb488
Create Date: 2015-10-19 12:28:07.426426

"""

# revision identifiers, used by Alembic.
revision = '3471f466dda'
down_revision = '734acfb488'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('uuid', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('oauth_token', sa.String(), nullable=False),
    sa.Column('oauth_secret', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('uuid', name=op.f('pk_users'))
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    ### end Alembic commands ###
