"""redirects table

Revision ID: 734acfb488
Revises: 
Create Date: 2015-10-16 23:08:54.428168

"""

# revision identifiers, used by Alembic.
revision = '734acfb488'
down_revision = None
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('redirects',
    sa.Column('from_url', sa.String(length=23), nullable=False),
    sa.Column('to_url', sa.String(), nullable=False),
    sa.Column('times_accessed', sa.Integer(), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('from_url', name=op.f('pk_redirects'))
    )
    op.create_index(op.f('ix_redirects_from_url'), 'redirects', ['from_url'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_redirects_from_url'), table_name='redirects')
    op.drop_table('redirects')
    ### end Alembic commands ###
